name: CMake Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build_windows_cpu:
    name: build_windows_cpu
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_CUDA=OFF -DTEST_CUDA=OFF

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: cd ${{github.workspace}}/build && ctest

      - name: Demo
        run: cd ${{github.workspace}}/demo/bin/${{env.BUILD_TYPE}} && ./TinyTorch_demo.exe

  build_windows_gpu:
    name: build_windows_gpu
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.22

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_CUDA=ON -DTEST_CUDA=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#      - name: Test
#        run: cd ${{github.workspace}}/build && ctest
#
#      - name: Demo
#        run: cd ${{github.workspace}}/demo/bin/${{env.BUILD_TYPE}} && ./TinyTorch_demo.exe
